Wysiwyg:
  CookieHandling:
    cleanUp:
      dryrun: true
    showCookieDetails: true
    consentCookieName: 'cookieConsent'
    cookieGroups:
      technical:
        readOnly: true
        defaultValue: true
        cookies:
          cookie_consent:
            cookieName: 'cookieConsent'
            lifetime: '3 months'
          cookie_accepted:
            cookieName: 'cookieConsentAccepted'
            lifetime: '3 months'


Neos:
  Neos:
    fusion:
      autoInclude:
        Wysiwyg.CookieHandling: true

    modules:
      management:
        submodules:
          cookieLogModule:
            controller: \Wysiwyg\CookieHandling\Controller\CookieLogModuleController
            label: 'Cookie Log'
            icon: 'fas fa-cookie-bite'

  Flow:
    mvc:
      routes:
        'Wysiwyg.CookieHandling': true

    http:

      middlewares:
        # adds consent cookie to incoming request
        cookieConsent:
          middleware: Wysiwyg\CookieHandling\Domain\Http\Middleware\CookieConsentMiddleware
          position: 'start'

        # removes not-accepted cookies from internal cookie jar (after dispatch)
        cleanupCookies:
          middleware: Wysiwyg\CookieHandling\Domain\Http\Middleware\CookieCleanupMiddleware
          position: 'end'

        # updates cookie in internal jar with current settings when signature of cookie setting has changed
        cookieUpdateHandler:
          middleware: Wysiwyg\CookieHandling\Domain\Http\Middleware\CookieLifetimeUpdateMiddleware
          position: 'after cleanupCookies'

        # updates response with all cookies in jar
        cookieConsentHandler:
          middleware: Wysiwyg\CookieHandling\Domain\Http\Middleware\CookieConsentHandlerMiddleware
          position: 'after cookieUpdateHandler'

  Fusion:
    defaultContext:
      CookieHandling: Wysiwyg\CookieHandling\Eel\Helper\CookieConsentHelper
