Wysiwyg:
  CookieHandling:
    cleanUp:
      dryrun: true
    showCookieDetails: true
    consentCookieName: 'cookieConsent'
    cookieGroups:
      technical:
        readOnly: true
        defaultValue: true
        cookies:
          cookie_consent:
            cookieName: 'cookieConsent'
            lifetime: '3 months'
          cookie_accepted:
            cookieName: 'cookieConsentAccepted'
            lifetime: '3 months'


Neos:
  Neos:
    fusion:
      autoInclude:
        Wysiwyg.CookieHandling: true

    modules:
      management:
        submodules:
          cookieLogModule:
            controller: \Wysiwyg\CookieHandling\Controller\CookieLogModuleController
            label: 'Cookie Log'
            icon: 'fas fa-cookie-bite'

  Flow:
    mvc:
      routes:
        'Wysiwyg.CookieHandling': true

    http:

      middlewares:
        cookieConsent:
          middleware: Wysiwyg\CookieHandling\Domain\Http\Middleware\CookieConsentMiddleware
          position: start

        cookieConsentHandler:
          middleware: Wysiwyg\CookieHandling\Domain\Http\Middleware\CookieConsentHandlerMiddleware
          position: 'after cookieConsent'

# work in progress
#        postprocess:
#          chain:
#            cleanupCookies:
#              position: 'end'
#              component: Wysiwyg\CookieHandling\Domain\Http\CookieCleanupComponent
#
#            cookieUpdateHandler:
#              position: 'after cleanupCookies'
#              component: Wysiwyg\CookieHandling\Domain\Http\CookieLifetimeUpdateComponent

  Fusion:
    defaultContext:
      CookieHandling: Wysiwyg\CookieHandling\Eel\Helper\CookieConsentHelper
